server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
# http://backend:8000 es lo importante, backend no es una ip, es un nombre
# que resuelve docker internamente para la red interna. :)

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
    }

    location /health {
        proxy_pass http://backend:8000;
    }

    location /metrics {
        proxy_pass http://backend:8000;
    }

    location /version {
        proxy_pass http://backend:8000;
    }
}
