services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nombreContainer
    restart: always
    environment:
      POSTGRES_DB: nombreBase
      POSTGRES_USER: User
      POSTGRES_PASSWORD: Pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: