{
 "title": "Logs con Loki",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs del backend",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"utec-ia-backend\"}"
    }
   ]
  },
  {
   "title": "Logs del frontend / Nginx",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"utec-ia-frontend\"}"
    }
   ]
  },
  {
   "title": "Logs por contenedor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (container) (\r\n  count_over_time({container=~\"utec-ia-.*\"}[1m])\r\n)"
    }
   ]
  },
  {
   "title": "Errores backend - 5 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"utec-ia-backend\"} |= \"ERROR\" [5m])) or vector(0)"
    }
   ]
  },
  {
   "title": "Logs backend - 5 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"utec-ia-backend\"}[5m]))"
    }
   ]
  }
 ]
}