apiVersion: v1
kind: ServiceAccount
metadata:
  name: utec-ia-backend
  namespace: utec-ia-pilot
  labels:
    app.kubernetes.io/part-of: utec-ia
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utec-ia-frontend
  namespace: utec-ia-pilot
  labels:
    app.kubernetes.io/part-of: utec-ia
automountServiceAccountToken: false
